accumulate_grad_batches: 1
adafactor: false
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: O2
attention_dropout: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
cache_dir: ''
check_val_every_n_epoch: 1
checkpoint: webnlg-bart-base.ckpt
checkpoint_callback: true
config_name: ''
data_dir: /home/thesunsavior/t2kg2t/g2t/plms-graph2text/webnlg/data/webnlg
decoder_layerdrop: null
default_root_dir: null
deterministic: false
distributed_backend: null
do_predict: true
do_train: false
dropout: null
early_stop_callback: false
early_stopping_patience: -1
encoder_layerdrop: null
eval_batch_size: 8
eval_beams: 5
eval_max_gen_length: 384
fast_dev_run: false
fp16: false
fp16_opt_level: O2
freeze_embeds: false
freeze_encoder: false
git_sha: ''
gradient_clip_val: 0
label_smoothing: 0.0
learning_rate: 5.0e-05
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_gpu_memory: null
log_save_interval: 100
logger: true
logger_name: default
lr_scheduler: linear
max_epochs: 1000
max_source_length: 384
max_steps: null
max_target_length: 384
max_tokens_per_batch: null
min_epochs: 1
min_steps: null
model_name_or_path: facebook/bart-base
n_test: -1
n_train: -1
n_val: -1
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 4
output_dir: /home/thesunsavior/t2kg2t/g2t/plms-graph2text/webnlg/outputs/test_model
overfit_batches: 0.0
overfit_pct: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
row_log_interval: 50
save_top_k: 1
seed: 42
sortish_sampler: false
src_lang: ''
sync_batchnorm: false
task: graph2text
terminate_on_nan: false
test_checkpoint: webnlg-bart-base.ckpt
test_max_target_length: 384
test_percent_check: null
tgt_lang: ''
tokenizer_name: null
track_grad_norm: -1
train_batch_size: 32
train_percent_check: null
truncated_bptt_steps: null
val_check_interval: 1.0
val_max_target_length: 384
val_metric: null
val_percent_check: null
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
